import type { Driver } from "@/types/entities";

const FAR_FUTURE = "2027-03-01T00:00:00Z";
const SOON = "2026-08-05T00:00:00Z"; // < 30 jours après "aujourd'hui" mocké (2026-07-17)
const EXPIRED = "2026-06-30T00:00:00Z";

/**
 * ~8 conductrices mockées : types de véhicules variés, statuts variés,
 * certaines avec documents bientôt expirés ou déjà expirés.
 */
export const MOCK_DRIVERS: Driver[] = [
  {
    id: "drv-001",
    phone: "+22997112233",
    firstName: "Justine",
    lastName: "Aïkpé",
    cin: "CIN-BJ-0451122",
    licenseCategory: "B",
    criminalRecordDate: "2026-01-10T00:00:00Z",
    vehicleType: "voiture",
    plate: "AB-1234-RB",
    rating: 4.8,
    status: "active",
    documentsExpiry: { permit: FAR_FUTURE, insurance: FAR_FUTURE, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 187500,
    isOnline: true,
    isEsmfStar: true,
    zone: "Cotonou - Akpakpa",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière", "Relation passagère", "Gestion des urgences"],
    contractSignedAt: "2025-04-12T00:00:00Z",
    createdAt: "2025-04-01T09:00:00Z",
    last20RatingsAvg: 4.8,
  },
  {
    id: "drv-002",
    phone: "+22996223355",
    firstName: "Odile",
    lastName: "Sagbo",
    cin: "CIN-BJ-0452233",
    licenseCategory: "A3",
    criminalRecordDate: "2025-11-20T00:00:00Z",
    vehicleType: "moto",
    plate: "AC-5566-RB",
    rating: 4.3,
    status: "active",
    documentsExpiry: { permit: FAR_FUTURE, insurance: SOON, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 96000,
    isOnline: true,
    isEsmfStar: false,
    zone: "Abomey-Calavi",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière", "Relation passagère"],
    contractSignedAt: "2025-09-02T00:00:00Z",
    createdAt: "2025-08-20T09:00:00Z",
    last20RatingsAvg: 4.3,
  },
  {
    id: "drv-003",
    phone: "+22995334466",
    firstName: "Emeline",
    lastName: "Dansou",
    cin: "CIN-BJ-0453344",
    licenseCategory: "A",
    criminalRecordDate: "2026-02-15T00:00:00Z",
    vehicleType: "tricycle",
    plate: "AD-7788-RB",
    rating: 3.2,
    status: "active",
    documentsExpiry: { permit: FAR_FUTURE, insurance: FAR_FUTURE, criminalRecord: EXPIRED },
    monthlyEarnings: 64000,
    isOnline: false,
    isEsmfStar: false,
    zone: "Cotonou - Fidjrossè",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière"],
    contractSignedAt: "2025-12-01T00:00:00Z",
    createdAt: "2025-11-15T09:00:00Z",
    last20RatingsAvg: 3.2,
  },
  {
    id: "drv-004",
    phone: "+22994445577",
    firstName: "Pascaline",
    lastName: "Gbaguidi",
    cin: "CIN-BJ-0454455",
    licenseCategory: "B",
    criminalRecordDate: "2026-03-05T00:00:00Z",
    vehicleType: "voiture",
    plate: "AE-9900-RB",
    rating: 4.6,
    status: "pending",
    documentsExpiry: { permit: FAR_FUTURE, insurance: FAR_FUTURE, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 0,
    isOnline: false,
    isEsmfStar: false,
    zone: "Cotonou - Cadjèhoun",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: false },
      { label: "Formation sécurité", completed: false },
      { label: "Contrat signé", completed: false },
    ],
    trainingCompleted: [],
    createdAt: "2026-07-10T09:00:00Z",
    last20RatingsAvg: 0,
  },
  {
    id: "drv-005",
    phone: "+22993556688",
    firstName: "Honorine",
    lastName: "Loko",
    cin: "CIN-BJ-0455566",
    licenseCategory: "A3",
    criminalRecordDate: "2025-10-08T00:00:00Z",
    vehicleType: "moto",
    plate: "AF-3344-RB",
    rating: 4.1,
    status: "active",
    documentsExpiry: { permit: SOON, insurance: FAR_FUTURE, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 88000,
    isOnline: true,
    isEsmfStar: true,
    zone: "Abomey-Calavi - Godomey",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière", "Relation passagère", "Gestion des urgences"],
    contractSignedAt: "2025-06-14T00:00:00Z",
    createdAt: "2025-06-01T09:00:00Z",
    last20RatingsAvg: 4.1,
  },
  {
    id: "drv-006",
    phone: "+22992667799",
    firstName: "Clarisse",
    lastName: "Houénou",
    cin: "CIN-BJ-0456677",
    licenseCategory: "B",
    criminalRecordDate: "2025-09-22T00:00:00Z",
    vehicleType: "voiture",
    plate: "AG-1122-RB",
    rating: 2.9,
    status: "suspended",
    documentsExpiry: { permit: FAR_FUTURE, insurance: EXPIRED, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 41000,
    isOnline: false,
    isEsmfStar: false,
    zone: "Cotonou - Gbégamey",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière"],
    contractSignedAt: "2025-02-10T00:00:00Z",
    createdAt: "2025-01-20T09:00:00Z",
    last20RatingsAvg: 2.9,
  },
  {
    id: "drv-007",
    phone: "+22991778800",
    firstName: "Bienvenue",
    lastName: "Assogba",
    cin: "CIN-BJ-0457788",
    licenseCategory: "A",
    criminalRecordDate: "2026-04-01T00:00:00Z",
    vehicleType: "tricycle",
    plate: "AH-6655-RB",
    rating: 4.5,
    status: "active",
    documentsExpiry: { permit: FAR_FUTURE, insurance: FAR_FUTURE, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 72000,
    isOnline: true,
    isEsmfStar: false,
    zone: "Cotonou - Vedoko",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: true },
      { label: "Casier judiciaire", completed: true },
      { label: "Formation sécurité", completed: true },
      { label: "Contrat signé", completed: true },
    ],
    trainingCompleted: ["Sécurité routière", "Relation passagère"],
    contractSignedAt: "2026-01-05T00:00:00Z",
    createdAt: "2025-12-20T09:00:00Z",
    last20RatingsAvg: 4.5,
  },
  {
    id: "drv-008",
    phone: "+22990889911",
    firstName: "Reine",
    lastName: "Kindji",
    cin: "CIN-BJ-0458899",
    licenseCategory: "B",
    criminalRecordDate: "2026-05-11T00:00:00Z",
    vehicleType: "voiture",
    plate: "AI-4433-RB",
    rating: 0,
    status: "pending",
    documentsExpiry: { permit: FAR_FUTURE, insurance: FAR_FUTURE, criminalRecord: FAR_FUTURE },
    monthlyEarnings: 0,
    isOnline: false,
    isEsmfStar: false,
    zone: "Abomey-Calavi - Womey",
    registrationSteps: [
      { label: "Pièces d'identité", completed: true },
      { label: "Permis de conduire", completed: false },
      { label: "Casier judiciaire", completed: false },
      { label: "Formation sécurité", completed: false },
      { label: "Contrat signé", completed: false },
    ],
    trainingCompleted: [],
    createdAt: "2026-07-15T09:00:00Z",
    last20RatingsAvg: 0,
  },
];
