import type { User } from "@/types/entities";

/**
 * ~10 passagères mockées : mix standard / étudiante / avec comptes enfants.
 */
export const MOCK_USERS: User[] = [
  {
    id: "usr-001",
    phone: "+22997001122",
    firstName: "Adjoavi",
    lastName: "Dossou",
    isStudentVerified: false,
    studentVerificationStatus: "none",
    emergencyContacts: [{ name: "Fifamè Dossou", phone: "+22997001199" }],
    loyaltyPoints: 42,
    status: "active",
    zone: "Cotonou - Akpakpa",
    accountType: "standard",
    createdAt: "2025-11-02T08:12:00Z",
    childAccounts: [],
  },
  {
    id: "usr-002",
    phone: "+22996223344",
    firstName: "Chimène",
    lastName: "Houngbo",
    isStudentVerified: true,
    studentVerificationStatus: "approved",
    studentCardUrl: "/mock/carte-etudiante-002.jpg",
    emergencyContacts: [{ name: "Marcelline Houngbo", phone: "+22996223300" }],
    loyaltyPoints: 128,
    status: "active",
    zone: "Abomey-Calavi",
    accountType: "student",
    createdAt: "2025-09-14T10:30:00Z",
    childAccounts: [],
  },
  {
    id: "usr-003",
    phone: "+22995334455",
    firstName: "Rachidatou",
    lastName: "Alassane",
    isStudentVerified: false,
    studentVerificationStatus: "pending",
    studentCardUrl: "/mock/carte-etudiante-003.jpg",
    emergencyContacts: [{ name: "Issa Alassane", phone: "+22995334400" }],
    loyaltyPoints: 15,
    status: "active",
    zone: "Cotonou - Fidjrossè",
    accountType: "student",
    createdAt: "2026-06-20T14:05:00Z",
    childAccounts: [],
  },
  {
    id: "usr-004",
    phone: "+22994445566",
    firstName: "Bernadette",
    lastName: "Ahouansou",
    isStudentVerified: false,
    studentVerificationStatus: "none",
    emergencyContacts: [
      { name: "Prudence Ahouansou", phone: "+22994445500" },
      { name: "Gérard Ahouansou", phone: "+22994445501" },
    ],
    loyaltyPoints: 210,
    status: "active",
    zone: "Cotonou - Cadjèhoun",
    accountType: "withChildren",
    createdAt: "2025-05-18T09:00:00Z",
    childAccounts: [
      {
        id: "chd-001",
        parentId: "usr-004",
        firstName: "Elikya",
        lastName: "Ahouansou",
        age: 9,
        school: "École primaire Sainte-Rita",
      },
      {
        id: "chd-002",
        parentId: "usr-004",
        firstName: "Fabrice",
        lastName: "Ahouansou",
        age: 12,
        school: "CEG Cadjèhoun",
      },
    ],
  },
  {
    id: "usr-005",
    phone: "+22993556677",
    firstName: "Sandrine",
    lastName: "Kpossou",
    isStudentVerified: false,
    studentVerificationStatus: "rejected",
    studentCardUrl: "/mock/carte-etudiante-005.jpg",
    emergencyContacts: [{ name: "Judicaël Kpossou", phone: "+22993556600" }],
    loyaltyPoints: 8,
    status: "suspended",
    zone: "Abomey-Calavi - Godomey",
    accountType: "standard",
    createdAt: "2026-01-11T16:45:00Z",
    childAccounts: [],
  },
  {
    id: "usr-006",
    phone: "+22992667788",
    firstName: "Nadège",
    lastName: "Zinsou",
    isStudentVerified: true,
    studentVerificationStatus: "approved",
    studentCardUrl: "/mock/carte-etudiante-006.jpg",
    emergencyContacts: [{ name: "Odile Zinsou", phone: "+22992667700" }],
    loyaltyPoints: 65,
    status: "active",
    zone: "Cotonou - Sainte-Rita",
    accountType: "student",
    createdAt: "2025-12-03T11:22:00Z",
    childAccounts: [],
  },
  {
    id: "usr-007",
    phone: "+22991778899",
    firstName: "Colette",
    lastName: "Agbodjan",
    isStudentVerified: false,
    studentVerificationStatus: "none",
    emergencyContacts: [{ name: "Herbert Agbodjan", phone: "+22991778800" }],
    loyaltyPoints: 300,
    status: "active",
    zone: "Cotonou - Akpakpa",
    accountType: "withChildren",
    createdAt: "2025-03-27T07:50:00Z",
    childAccounts: [
      {
        id: "chd-003",
        parentId: "usr-007",
        firstName: "Merveille",
        lastName: "Agbodjan",
        age: 7,
        school: "École Les Flamboyants",
      },
    ],
  },
  {
    id: "usr-008",
    phone: "+22990889900",
    firstName: "Larissa",
    lastName: "Tossou",
    isStudentVerified: false,
    studentVerificationStatus: "none",
    emergencyContacts: [{ name: "Yvette Tossou", phone: "+22990889901" }],
    loyaltyPoints: 3,
    status: "disabled",
    zone: "Cotonou - Gbégamey",
    accountType: "standard",
    createdAt: "2026-04-02T13:15:00Z",
    childAccounts: [],
  },
  {
    id: "usr-009",
    phone: "+22989990011",
    firstName: "Wilhelmine",
    lastName: "Adjovi",
    isStudentVerified: false,
    studentVerificationStatus: "pending",
    studentCardUrl: "/mock/carte-etudiante-009.jpg",
    emergencyContacts: [{ name: "Théophile Adjovi", phone: "+22989990000" }],
    loyaltyPoints: 21,
    status: "active",
    zone: "Abomey-Calavi - Womey",
    accountType: "student",
    createdAt: "2026-07-01T09:40:00Z",
    childAccounts: [],
  },
  {
    id: "usr-010",
    phone: "+22988001122",
    firstName: "Prisca",
    lastName: "Sossou",
    isStudentVerified: false,
    studentVerificationStatus: "none",
    emergencyContacts: [{ name: "Blandine Sossou", phone: "+22988001100" }],
    loyaltyPoints: 54,
    status: "active",
    zone: "Cotonou - Vedoko",
    accountType: "standard",
    createdAt: "2025-08-09T18:05:00Z",
    childAccounts: [],
  },
];
